changelog:
  categories:
    - title: Bugs fixes 🛠
      labels:        
        - bug
    - title: New Features 🎉
      labels:        
        - enhancement
        - tui
    - title: Other Changes
      labels:
        - "*"
