[package]
name = "pik"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.28"
ratatui = "0.27"
anyhow = "1.0.79"
sysinfo = "0.31"
listeners = "0.2.1"
chrono = "0.4"
